apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: tenant-management
spec:
  mtls:
    mode: PERMISSIVE # Allow both mTLS and plain text for gradual rollout
