apiVersion: v1
items:
- apiVersion: v1
  data:
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
    DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vcG9zdGdyZXM6cG9zdGdyZXNAcG9zdGdyZXMtc2VydmljZTo1NDMyL3RlbmFudF9tYW5hZ2VtZW50
    KEYCLOAK_ADMIN_PASSWORD: YWRtaW4xMjM=
    KEYCLOAK_ADMIN_USERNAME: YWRtaW4=
    KEYCLOAK_CLIENT_SECRET: eW91ci1jbGllbnQtc2VjcmV0LWNoYW5nZS1pbi1wcm9kdWN0aW9u
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"backend-secret","namespace":"tenant-management"},"stringData":{"AWS_ACCESS_KEY_ID":"","AWS_SECRET_ACCESS_KEY":"","DATABASE_URL":"postgresql+asyncpg://postgres:postgres@postgres-service:5432/tenant_management","KEYCLOAK_ADMIN_PASSWORD":"admin123","KEYCLOAK_ADMIN_USERNAME":"admin","KEYCLOAK_CLIENT_SECRET":"your-client-secret-change-in-production"},"type":"Opaque"}
    creationTimestamp: "2026-01-01T13:01:14Z"
    name: backend-secret
    namespace: tenant-management
    resourceVersion: "192633636"
    uid: f545ef19-fc91-47c7-92a6-8114a8ff69ba
  type: Opaque
- apiVersion: v1
  data:
    KC_DB_PASSWORD: a2V5Y2xvYWsxMjM=
    KC_DB_USERNAME: a2V5Y2xvYWs=
    KEYCLOAK_ADMIN: YWRtaW4=
    KEYCLOAK_ADMIN_PASSWORD: YWRtaW4xMjM=
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"keycloak-secrets","namespace":"tenant-management"},"stringData":{"KC_DB_PASSWORD":"keycloak123","KC_DB_USERNAME":"keycloak","KEYCLOAK_ADMIN":"admin","KEYCLOAK_ADMIN_PASSWORD":"admin123"},"type":"Opaque"}
    creationTimestamp: "2026-01-03T06:42:30Z"
    name: keycloak-secrets
    namespace: tenant-management
    resourceVersion: "192347553"
    uid: f60bb8d6-12a2-4fc2-8457-bd365172f58d
  type: Opaque
- apiVersion: v1
  data:
    POSTGRES_DB: dGVuYW50X21hbmFnZW1lbnQ=
    POSTGRES_PASSWORD: cG9zdGdyZXM=
    POSTGRES_USER: cG9zdGdyZXM=
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"postgres-secret","namespace":"tenant-management"},"stringData":{"POSTGRES_DB":"tenant_management","POSTGRES_PASSWORD":"postgres","POSTGRES_USER":"postgres"},"type":"Opaque"}
    creationTimestamp: "2026-01-01T13:01:14Z"
    name: postgres-secret
    namespace: tenant-management
    resourceVersion: "190662459"
    uid: 68372038-9523-466d-b74a-d58509ade590
  type: Opaque
- apiVersion: v1
  data:
    POSTGRES_PASSWORD: a2V5Y2xvYWsxMjM=
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"postgres-secrets","namespace":"tenant-management"},"stringData":{"POSTGRES_PASSWORD":"keycloak123"},"type":"Opaque"}
    creationTimestamp: "2026-01-03T06:42:32Z"
    name: postgres-secrets
    namespace: tenant-management
    resourceVersion: "192347567"
    uid: 360e5507-219f-407b-9d2a-e9a1bcf1c1e2
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
